'use client';

import type { ReactNode } from 'react';
import './glossary-term.css';

const definitions = {
  AEO: 'Answer engine optimization: shaping content so AI search tools can find, understand and cite it.',
  AOV: 'Average order value: net order revenue divided by completed orders.',
  BI: 'Business intelligence: governed reporting that turns source-system data into decision-ready views.',
  CAC: 'Customer acquisition cost: acquisition spend divided by genuinely new customers.',
  COGS: 'Cost of goods sold: the direct product cost recognized for items sold.',
  CPA: 'Cost per acquisition: advertising spend divided by attributed acquisition actions; it is not always the same as fully loaded CAC.',
  CRM: 'Customer relationship management: the customer profiles, consent and lifecycle messaging system.',
  CVR: 'Conversion rate: the share of eligible visits or sessions that complete the target action.',
  DTC: 'Direct to consumer: sales made through a brand-owned storefront or customer relationship.',
  GA4: 'Google Analytics 4: Google’s event-based website and app analytics product.',
  GMV: 'Gross merchandise value: merchandise value before deductions such as returns or fees.',
  GSC: 'Google Search Console: Google’s first-party reporting for organic queries, impressions, clicks, pages and indexation.',
  KPI: 'Key performance indicator: a governed metric tied to an operating decision.',
  LTV: 'Lifetime value: the economic value generated by a customer across the agreed time horizon.',
  MER: 'Marketing efficiency ratio: total net revenue divided by total marketing spend.',
  MRR: 'Monthly recurring revenue: predictable subscription revenue normalized to one month.',
  NTB: 'New to brand: a customer or order not previously observed for the brand in the agreed lookback window.',
  OKR: 'Objective and key result: an outcome-led goal with measurable evidence of progress.',
  PDP: 'Product detail page: the storefront page where a shopper evaluates and buys one product.',
  PO: 'Purchase order: the approved commitment authorizing spend with a vendor.',
  ROAS: 'Return on ad spend: attributed revenue divided by advertising spend for the same scope and window.',
  ROI: 'Return on investment: incremental profit or value compared with the total investment required.',
  SEO: 'Search engine optimization: improving discoverability and usefulness in organic search results.',
  SKU: 'Stock keeping unit: the unique identifier for a sellable product variant.',
  UTM: 'Urchin Tracking Module: campaign parameters added to a URL to preserve acquisition source and campaign context.',
} as const;

export type GlossaryTermName = keyof typeof definitions;

export function MetricTerm({ term }: { term: GlossaryTermName }) {
  const definition = definitions[term];
  return (
    <button
      type="button"
      className="metric-term"
      data-definition={definition}
      aria-label={`${term}: ${definition}`}
      title={`${term}: ${definition}`}
    >
      {term}
    </button>
  );
}

const glossaryPattern = new RegExp(
  `\\b(${Object.keys(definitions)
    .sort((a, b) => b.length - a.length)
    .join('|')})\\b`,
  'g',
);

export function GlossaryText({ children }: { children: string }): ReactNode {
  return children.split(glossaryPattern).map((part, index) => {
    if (part in definitions) {
      return (
        <MetricTerm key={`${part}-${index}`} term={part as GlossaryTermName} />
      );
    }
    return part;
  });
}

export function GlossaryHint() {
  return (
    <p className="glossary-hint">
      <span aria-hidden="true">?</span>
      Hover, focus or tap an underlined term for its plain-English definition.
    </p>
  );
}
