import { ArrowUpRight, CalendarRange, CheckCircle2, CircleAlert, Database, Search, Video } from 'lucide-react';

const googleAdvertiser='https://adstransparency.google.com/advertiser/AR09480320723080708097?region=US';
const google2025=`${googleAdvertiser}&start-date=2025-01-01&end-date=2025-12-31`;
const google2026=`${googleAdvertiser}&start-date=2026-01-01&end-date=2026-09-08`;
const metaLibrary='https://www.facebook.com/ads/library/?active_status=all&ad_type=all&country=US&q=Kitsch&search_type=keyword_unordered';

const googleAds=[
  {type:'SEARCH + IMAGE ASSET',title:'“Kitsch™ Hair Growth Products”',window:'Present in the 2025 archive filter · last shown Sep 8, 2026',observed:'Category-led headline, Rice Water Shampoo Bar image, large review proof, rating and return-policy assets.',read:'A durable bridge from a broad hair-growth need to a recognizable hero product and merchant proof.',test:'Brand vs non-brand query mix · impression share · new-to-brand CAC · contribution',href:'https://adstransparency.google.com/advertiser/AR09480320723080708097/creative/CR00373618526474207233?region=US'},
  {type:'SHOPPING / PRODUCT LISTING',title:'Rice Water Shampoo Bar for Hair Growth',window:'Present in the 2025 archive filter · last shown Sep 8, 2026',observed:'A precise product-feed ad pairs the category phrase with the recognizable bar pack shot.',read:'Feed architecture is doing conversion work: title clarity and product imagery answer “what is it?” immediately.',test:'Search term → SKU · feed disapprovals · price competitiveness · margin after returns',href:'https://adstransparency.google.com/advertiser/AR09480320723080708097/creative/CR12400881115512963073?region=US'},
  {type:'RESPONSIVE SEARCH',title:'Claw clips: evergreen + promotion variants',window:'Three visible variations · last shown Sep 8, 2026',observed:'One variation leads with the category; another adds “Save 30% Sitewide,” while review, rating and return assets persist.',read:'The structure can separate category capture from promotional pressure without losing merchant reassurance.',test:'Incremental conversion · full-price mix · new-customer rate · post-promo repeat',href:'https://adstransparency.google.com/advertiser/AR09480320723080708097/creative/CR09942174267409956865?region=US'},
] as const;

const metaAds=[
  {status:'ACTIVE',date:'Started Jun 5, 2026',id:'1774860456878244',title:'Air Dry Cream: problem → mechanism',format:'51s video; a separate 16s execution was also visible',observed:'“Frizz? Never heard of her” opens the problem, then explains zero-heat styling and ingredient support.',read:'A strong concept system can hold the same promise across education and shorter conversion edits.',test:'Hook hold · qualified CTR · PDP CVR · return reason · repeat',href:metaLibrary},
  {status:'ACTIVE',date:'Started Jun 5, 2026',id:'2152225562292076',title:'Hair perfume: category education + choice',format:'36s video',observed:'Introduces patented odor-eliminating technology, the between-wash occasion, layering and scent personalities.',read:'The ad reduces uncertainty in a newer category while turning variety into an exploration mechanic.',test:'New-to-brand rate · discovery-set attach · full-size migration · 60-day repeat',href:metaLibrary},
  {status:'ACTIVE',date:'Started Jun 17, 2026',id:'1336829075084639',title:'Shampoo + conditioner: claim stack',format:'71s video; multiple versions visible',observed:'Launch framing leads into a quantified five-wash volume claim, shine, damage prevention and formulation proof.',read:'This is the clearest public example of Kitsch moving from reaction to substantiated product evidence.',test:'Claim-coded CVR · landing congruence · complaint rate · cohort contribution',href:metaLibrary},
  {status:'INACTIVE',date:'Apr 20–May 19, 2026',id:'1351444956814929',title:'Leave-in: customer voice + quantified proof',format:'54s video; four ads used the creative/text',observed:'A detailed customer testimonial is followed by a 35% softness claim and format reassurance.',read:'Customer language handles skepticism while the quantified claim gives the creative a proof anchor.',test:'Testimonial vs mechanism lift · claim comprehension · assisted conversion',href:metaLibrary},
  {status:'INACTIVE',date:'Apr 4–May 19, 2026',id:'1251417430411508',title:'Heatless: compressed benefit promise',format:'73s video; three ads used the creative/text',observed:'“0% Heat · 0% Damage · 0% Effort” compresses the category’s functional promise into three memorable lines.',read:'The message is highly portable across video, search and retail—but each claim still needs approved substantiation.',test:'Concept recall · click quality · hair-type fit · return rate',href:metaLibrary},
] as const;

function External({href,children}:{href:string;children:React.ReactNode}){return <a className="source-link" href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={13}/></a>}
function Signal({children}:{children:string}){return <span className="signal public">{children}</span>}

export function PaidMediaEvidence(){return <>
  <section className="wide-card paid-evidence-head"><div><p>OFFICIAL PAID-MEDIA TRANSPARENCY</p><h2>Strategically notable ads—not proven winners</h2><span>Google and Meta show creative, formats and serving dates. They do not expose Kitsch’s US commercial spend, targeting, conversions, CAC, ROAS or profit.</span></div><Signal>PUBLIC SIGNAL</Signal></section>
  <section className="paid-audit-strip"><article><Search/><strong>~700</strong><span>Google ads · verified Kitsch LLC advertiser · any time</span></article><article><CalendarRange/><strong>~400</strong><span>Google ads returned for Jan–Dec 2025</span></article><article><CalendarRange/><strong>~600</strong><span>Google ads returned for Jan 1–Sep 8, 2026</span></article><article><Video/><strong>5</strong><span>selected Meta concept examples reviewed in detail</span></article></section>
  <section className="wide-card"><div className="paid-section-title"><div><span>GOOGLE ADS TRANSPARENCY CENTER</span><h3>Historical persistence + intent capture</h3><p>The same creative IDs appearing in the 2025 filtered archive and showing a Sep. 8, 2026 last-served date are longevity signals. Longevity can reflect usefulness, automation or reuse; it is not proof of efficiency.</p></div><div><External href={google2025}>2025 archive</External><External href={google2026}>2026 YTD</External></div></div><div className="ad-evidence-grid google">{googleAds.map((ad,i)=><article key={ad.title}><div><span>0{i+1} · {ad.type}</span><Signal>PUBLIC SIGNAL</Signal></div><h3>{ad.title}</h3><small>{ad.window}</small><dl><dt>What is visible</dt><dd>{ad.observed}</dd><dt>Strategic read</dt><dd>{ad.read}</dd><dt>Validate with</dt><dd>{ad.test}</dd></dl><External href={ad.href}>View official creative</External></article>)}</div></section>
  <section className="wide-card"><div className="paid-section-title"><div><span>META AD LIBRARY · KITSCH PAGE CARDS IN US SEARCH</span><h3>Problem, proof and product education</h3><p>Selected active and inactive examples preserve the public message, format, visible start/end dates and Library ID. “Multiple versions” and reuse counts describe library structure—not audience reach.</p></div><External href={metaLibrary}>Open Meta search</External></div><div className="ad-evidence-grid meta">{metaAds.map((ad,i)=><article key={ad.id}><div><span>0{i+1} · {ad.status}</span><small>{ad.date}</small></div><h3>{ad.title}</h3><p>{ad.format}</p><dl><dt>What is visible</dt><dd>{ad.observed}</dd><dt>Strategic read</dt><dd>{ad.read}</dd><dt>Validate with</dt><dd>{ad.test}</dd></dl><a className="library-id" href={ad.href} target="_blank" rel="noreferrer">META LIBRARY ID · {ad.id}<ArrowUpRight/></a></article>)}</div></section>
  <section className="two-col"><article className="wide-card"><h3 className="paid-subhead">How to apply this to Kitsch</h3><ul className="commerce-list"><li><CheckCircle2/>Code each concept by problem, product, awareness stage, proof, offer, format and landing page.</li><li><CheckCircle2/>Treat edits and aspect ratios as variants; count distinct customer ideas separately.</li><li><CheckCircle2/>Preserve start, stop and last-seen dates in a monthly creative ledger.</li><li><CheckCircle2/>Require every scaled concept to state what was learned and where it will be reused.</li></ul></article><article className="wide-card"><h3 className="paid-subhead">The performance bridge</h3><div className="paid-data-bridge"><Database/><p>Creative ID → spend → impressions → qualified click → new-to-brand order → realized contribution → 30/60/90-day repeat.</p></div><div className="method-note"><CircleAlert/><p>Without this first-party join, the report can identify useful creative patterns and competitive pressure—but cannot rank the “best” ads.</p></div><span className="signal internal">INTERNAL DATA REQUIRED</span></article></section>
  </>}
